version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./SampleCollections:/usr/local/sampleCollections
      - mongo-data:/data/db
    working_dir: /usr/local/sampleCollections

  server:
    image: node:alpine
    volumes:
      - ./:/usr/local/server
    working_dir: /usr/local/server
    environment:
      - PORT=4000
      - MONGO_URL=mongodb://root:password@mongo:27017/app?authSource=admin
      - DATABASE_URL=postgres://root:password@db/app
      - JWT_SECRET=secret
    ports:
      - "127.0.0.1:4000:4000"
    command: sh -c "apk add --update make && npm install --workspace=server && make start-server"

  front:
    image: node:alpine
    volumes:
      - ./:/usr/local/front
    working_dir: /usr/local/front
    environment:
      - PORT=3000
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:3010:3010"
    command: sh -c "apk add --update make && npm install --workspace=front && make start-front"


  db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

volumes:
  mongo-data: {}
  db-data: {}