###
PUT http://localhost:4000/api/users/2/messages/54
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlRlc3QiLCJpYXQiOjE2NTg2ODUzMjEsImV4cCI6MTY5MDI0MjkyMX0.8zGP5FucfaHLLXOE8lzi9ftObYhiqkufDNu-fiMENgEDbXgDue7oehwkDHUga5w8KpdZHRjSkpkKwLakr2z_6w

{
  "text": "Bah ouais t'es con frérot ",
  "is_read": false,
  "is_deleted" : true
}
