###
POST http://localhost:4000/api/users/1/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlRlc3QiLCJpYXQiOjE2NTg0MTM5NTQsImV4cCI6MTY4OTk3MTU1NH0.6G6ji5Sio16me-DAPqS7GR7lH4fb6B-mwIkdVsqdXrfNd1B83PvBz1RL4fjQCmRo4HOavcnivwMQg9sJngPHMQ

{
  "sendToId": 3,
  "text": "Salut! Comment tu vas ?",
  "is_read": false
}